version: '3'

services:
  dks-registry:
    image: registry:latest
    container_name: dks-registry
    volumes:
      - ./vol/registry:/var/lib/registry
    ports:
      - "55010:5000"
    restart: unless-stopped
    
